# Dockerfile

FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY dashboard/ ./dashboard/

EXPOSE 3000

CMD ["streamlit", "run", "dashboard/streamlit_app.py", "--server.port=6379", "--server.address=0.0.0.0"]